/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto.poo.films;

import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mycompany.projeto.poo.manipulacao.Manipulacao;

/**
 *
 * @author pedroupcm
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form EditarFilmes
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoNomew = new javax.swing.JLabel();
        inserirNome = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarFilme = new javax.swing.JTable();
        textoNovoNome = new javax.swing.JLabel();
        textoNovosAtores = new javax.swing.JLabel();
        textoNovoGenero = new javax.swing.JLabel();
        textoNovaClassificacao = new javax.swing.JLabel();
        textoNovoPreco = new javax.swing.JLabel();
        inserirNovoTitulo = new javax.swing.JTextField();
        inserirNovosAtores = new javax.swing.JTextField();
        inserirNovoGenero = new javax.swing.JTextField();
        inserirNovaClassificacao = new javax.swing.JTextField();
        inserirNovoPreco = new javax.swing.JTextField();
        botaoEnviar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoNomew.setText("Nome do Filme :");

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        mostrarFilme.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Titulo", "Atores", "Genero", "Classificação", "Preço"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(mostrarFilme);

        textoNovoNome.setText("Novo titulo :");

        textoNovosAtores.setText("Novos atores :");

        textoNovoGenero.setText("Novo genero :");

        textoNovaClassificacao.setText("Nova classificação :");

        textoNovoPreco.setText("Novo preço :");

        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoNomew)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inserirNome, javax.swing.GroupLayout.DEFAULT_SIZE, 147,
                                                        Short.MAX_VALUE)
                                                .addGap(27, 27, 27)
                                                .addComponent(botaoPesquisar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoNovoNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inserirNovoTitulo))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoNovosAtores)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inserirNovosAtores))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoNovoGenero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inserirNovoGenero))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoNovoPreco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inserirNovoPreco))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoNovaClassificacao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inserirNovaClassificacao))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(botaoEnviar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botaoSair)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoNomew)
                                        .addComponent(inserirNome, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoPesquisar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoNovoNome)
                                        .addComponent(inserirNovoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoNovosAtores)
                                        .addComponent(inserirNovosAtores, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoNovoGenero)
                                        .addComponent(inserirNovoGenero, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textoNovaClassificacao)
                                        .addComponent(inserirNovaClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoNovoPreco)
                                        .addComponent(inserirNovoPreco, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botaoEnviar)
                                        .addComponent(botaoSair))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoPesquisarActionPerformed
        String nome = inserirNome.getText();

        String pesquisa = nome + "\t";
        String preencher = "";
        File filme = new File(Manipulacao.DB_FILMES + "filmes.txt");

        String[] lines = Manipulacao.lerArquivo(filme).split("\n");

        for (String line : lines) {
            String aux = line.split("\t")[0] + "\t";
            if (aux.equals(pesquisa)) {
                preencher = line.split("\t")[0] + "\t" + line.split("\t")[1] + "\t" + line.split("\t")[2] + "\t"
                        + line.split("\t")[3] + "\t" + line.split("\t")[4] + "\n";
                break;
            }
        }

        DefaultTableModel modelo = (DefaultTableModel) mostrarFilme.getModel();
        if (modelo.getRowCount() > 0) {
            modelo.setRowCount(0);
        }

        Object[] obj = preencher.split("\t");
        modelo.addRow(obj);
    }// GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoSairActionPerformed
        dispose();
    }// GEN-LAST:event_botaoSairActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEnviarActionPerformed
        String titulo = inserirNome.getText();
        String atores = "";
        String genero = "";
        String classificacao = "";
        String preco = "";
        String dadosAntigos = titulo + "\t";

        File temp = new File(Manipulacao.DB_FILMES + "filmes.txt");
        String[] lines = Manipulacao.lerArquivo(temp).split("\n");

        for (String line : lines) {
            String aux = line.split("\t")[0] + "\t";
            if (aux.equals(dadosAntigos)) {
                // 0 = titulo , ja tem o titulo
                atores = line.split("\t")[1];
                genero = line.split("\t")[2];
                classificacao = line.split("\t")[3];
                preco = line.split("\t")[4];
                break;
            }
        }

        String tituloNovo = inserirNovoTitulo.getText();
        String atoresNovo = inserirNovosAtores.getText();
        String generoNovo = inserirNovoGenero.getText();
        String classificacaoNovo = inserirNovaClassificacao.getText();
        String precoNovo = inserirNovoPreco.getText();
        if (inserirNovoTitulo.getText().equals("")) {
            tituloNovo = titulo;
        }
        if (inserirNovosAtores.getText().equals("")) {
            atoresNovo = atores;
        }
        if (inserirNovoGenero.getText().equals("")) {
            generoNovo = genero;
        }
        if (inserirNovaClassificacao.getText().equals("")) {
            classificacaoNovo = classificacao;
        }
        if (inserirNovoPreco.getText().equals("")) {
            precoNovo = preco;
        }
        String dadosNovos = tituloNovo + "\t" + atoresNovo + "\t" + generoNovo + "\t" + classificacaoNovo + "\t"
                + precoNovo + "\n";

        File filme = new File(Manipulacao.DB_FILMES + "filmes.txt");

        try {
            Manipulacao.alterarDadosArquivoFilme(filme, dadosAntigos, dadosNovos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO");
        }

        JOptionPane.showMessageDialog(rootPane, "Dados do filme " + tituloNovo + " Alterados com sucesso !");
        dispose();
    }// GEN-LAST:event_botaoEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void editarfilmes(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField inserirNome;
    private javax.swing.JTextField inserirNovaClassificacao;
    private javax.swing.JTextField inserirNovoGenero;
    private javax.swing.JTextField inserirNovoPreco;
    private javax.swing.JTextField inserirNovoTitulo;
    private javax.swing.JTextField inserirNovosAtores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mostrarFilme;
    private javax.swing.JLabel textoNomew;
    private javax.swing.JLabel textoNovaClassificacao;
    private javax.swing.JLabel textoNovoGenero;
    private javax.swing.JLabel textoNovoNome;
    private javax.swing.JLabel textoNovoPreco;
    private javax.swing.JLabel textoNovosAtores;
    // End of variables declaration//GEN-END:variables
}
